### ISSUE TITLE
Disable buttons when Revolution has expired

### ISSUE THREAD

**Issue by AndreiCiobircaTUD** [ESloman/bsebot#122]
This is my first issue and I'm just testing it out. 

Once the resolution has ended, all buttons will be disabled.

**Comment by ESloman** [comment]
Bumping to `v2.3.0` as unlikely it'll get done for `v2.2.0`.

**Comment by ESloman** [comment]
Another solution; just edit the message to get rid of the view. Probably a simpler solution.

**Comment by ESloman** [comment]
Assigning to me so it actually gets done.
