### ISSUE TITLE
Supporting King gets taxed less

### ISSUE THREAD

**Issue by AndreiCiobircaTUD** [ESloman/bsebot#268]
As the title suggests, if you decide to support he king you get taxed less but if you overthrow you get taxed more.

**Comment by ESloman** [comment]
Supporters/revolutionaries can get added to the DB in the specific server document. We can use that to work out who's what. Additionally, can assign a `Supporter` role or a `Revolutionary` role depending on their stance.

**Comment by ESloman** [comment]
Implementing this at the moment
